Fix for generating report from multiple different databases
dell/cert-csi pull request #33
Opened 2023-08-09 17:05 UTC by suryagupta4

# Description
Fixed the generation of report for the test runs from multiple different databases

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/921 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran make test 
![image](https://github.com/dell/cert-csi/assets/109594002/2df2c9b1-c4c9-4f1f-8c90-fa070453be1f)

- [x] Verified by generating report for multiple test runs from different databases. No errors received.
![image](https://github.com/dell/cert-csi/assets/109594002/1ca1e5b6-215a-44ad-960d-29e36e3060ae)
![image](https://github.com/dell/cert-csi/assets/109594002/8c74eb66-499c-45fb-a522-96021d5e6d3d)

2023-08-10 04:48 UTC, adarsh-dell commented on pkg/reporter/reporter.go
> +				continue
Will it be okay to add some debug/warn level log message, In case if we are unable to process the metric for some of SC/DB.

2023-08-10 05:13 UTC, AkshaySainiDell requested changes

2023-08-10 05:13 UTC, AkshaySainiDell commented on pkg/reporter/reporter.go
> +			}
I agree with @adarsh-dell. Along with logger you can move line 131 inside this if block. This was we can remove testRunFound variable.
```suggestion
			if err != nil {
				log.Warnf("A warning message..")
				invalidTestRuns = append(invalidTestRuns, testRun)
				continue
			}
```

2023-08-21 07:16 UTC, AkshaySainiDell approved these changes
lgtm

2023-08-21 08:17 UTC, adarsh-dell approved these changes

2023-08-21 08:18 UTC, merged